function [problematic_stage_output_tile_relative_paths, problematic_stage_output_tile_messages] = ...
        check_raw_tile(stage_root_folder_path, ...
                       tile_file_relative_path, ...
                       nominal_raw_tif_file_size, ...
                       nominal_tile_shape_yxz, ...                       
                       problematic_stage_output_tile_relative_paths, ...
                       problematic_stage_output_tile_messages)
                                      
    tile_file_absolute_path = fullfile(stage_root_folder_path, tile_file_relative_path) ;
    tile_file_size = get_file_size(tile_file_absolute_path) ;
    if isequal(tile_file_size, nominal_raw_tif_file_size) ,
        % all is well, do nothing
    else
        % If we get here, it might be a 'short stack', one with too few z slices, or
        % it might be a patched short stack (which is fine, but has
        % different metadata than untouched stacks), so we investigate further...
        try
            [tile_shape, bits_per_pixel] = get_tiff_shape(tile_file_absolute_path) ;
        catch me  %#ok<NASGU>
            problematic_stage_output_tile_relative_paths = ...
                horzcat(problematic_stage_output_tile_relative_paths, ...
                        tile_file_relative_path) ;
            problematic_stage_output_tile_messages = ...
                horzcat(problematic_stage_output_tile_messages, ...
                        sprintf('Could not obtain shape, bits-per-pixel of %s', ...
                                tile_file_relative_path)) ;
            return                
        end
        if ~isequal(tile_shape, nominal_tile_shape_yxz) ,
            problematic_stage_output_tile_relative_paths = ...
                horzcat(problematic_stage_output_tile_relative_paths, ...
                        tile_file_relative_path) ;
            problematic_stage_output_tile_messages = ...
                horzcat(problematic_stage_output_tile_messages, ...
                        sprintf('%s is the wrong shape, shape (yxz) is [%d %d %d]', ...
                                tile_file_relative_path, ...
                                tile_shape)) ;
        else
            if bits_per_pixel ~= 16 ,
                problematic_stage_output_tile_relative_paths = ...
                    horzcat(problematic_stage_output_tile_relative_paths, ...
                            tile_file_relative_path) ;
                problematic_stage_output_tile_messages = ...
                    horzcat(problematic_stage_output_tile_messages, ...
                            sprintf('%s has %d bits per pixel, should have 16', ...
                                    tile_file_relative_path, ...
                                    bits_per_pixel)) ;
            end
        end
    end
end
