function [tile_index_from_tile_ijk1, ...
          tile_ijk1_from_tile_index, ...
          xyz_from_tile_index, ...
          relative_path_from_tile_index] = ...
        extract_tiles_near_tile(...
            full_tile_index_from_full_tile_ijk1, ...
            full_tile_ijk1_from_full_tile_index, ...
            xyz_from_full_tile_index, ...
            relative_path_from_full_tile_index, ...
            center_tile_relative_path) 

    is_center_tile_from_full_tile_index = strcmp(center_tile_relative_path, relative_path_from_full_tile_index) ;
    center_tile_full_index = find(is_center_tile_from_full_tile_index) ;
    center_tile_full_ijk1 = full_tile_ijk1_from_full_tile_index(center_tile_full_index, :) ;  %#ok<FNDSB>
    is_in_hood_from_full_tile_ijk1 = false(size(full_tile_index_from_full_tile_ijk1)) ;  % "hood" == "neighborhood" b/c I'm *very* street
    is_in_hood_from_full_tile_ijk1(center_tile_full_ijk1(1)-1:center_tile_full_ijk1(1)+1, ...
                                   center_tile_full_ijk1(2)-1:center_tile_full_ijk1(2)+1, ...
                                   center_tile_full_ijk1(3)-1:center_tile_full_ijk1(3)+1) = true ;
    
                               
    full_tile_index_from_tile_ijk1 = full_tile_index_from_full_tile_ijk1(is_in_hood_from_full_tile_ijk1) ;
    full_tile_index_from_tile_index = full_tile_index_from_tile_ijk1(:) ;
    
    full_tile_count  = length(relative_path_from_full_tile_index) ;
    tile_index_from_full_tile_index = invert_map_array(full_tile_index_from_tile_index, full_tile_count) ;
    tile_index_from_tile_ijk1 = tile_index_from_full_tile_index(full_tile_index_from_tile_ijk1) ;
    
    
    full_tile_ijk1_from_tile_index = full_tile_ijk1_from_full_tile_index(full_tile_index_from_tile_index, :) ;
    offset_ijk = min(full_tile_ijk1_from_tile_index, [] , 1) ;
    tile_ijk1_from_tile_index = full_tile_ijk1_from_tile_index - offset_ijk + 1 ;
    
    xyz_from_tile_index = xyz_from_full_tile_index(full_tile_index_from_tile_index,:) ;
    relative_path_from_tile_index = relative_path_from_full_tile_index(full_tile_index_from_tile_index) ;
end
