function find_and_batch(base_folder_path, file_name_regexp, batch_function, do_submit, varargin)
    job_ids = ...
        find_and_batch_helper(base_folder_path, ...
                              base_folder_path, ...
                              file_name_regexp, ...
                              batch_function, ...
                              do_submit, ...
                              zeros(1,0), ...
                              varargin{:}) ;
    job_statuses = bwait(job_ids) ;
    if all(job_statuses==1) ,
        fprintf('All %d batch jobs completed without errors.\n', length(job_ids)) ;
    else
        fprintf('All %d batch jobs exited, but some had errors.\n', length(job_ids)) ;
        had_error = (job_statuses==-1) ;
        bad_job_ids = job_ids(had_error) ;
        fprintf('Job ids with errors: %s\n', mat2str(bad_job_ids)) ;
    end
end



function job_ids = ...
        find_and_batch_helper(base_folder_path, ...
                              folder_path, ...
                              file_name_regexp, ...
                              batch_function, ...
                              do_submit, ...
                              initial_job_ids, ...
                              varargin)
    job_ids = initial_job_ids ;                                                 
    [directory_entries, is_directory_entry_a_folder] = simple_dir(folder_path) ;
    directory_entry_count_count = length(directory_entries) ;
    for i = 1 : directory_entry_count_count ,
        directory_entry = directory_entries{i} ;
        is_this_directory_entry_a_folder = is_directory_entry_a_folder(i) ;
        directory_entry_path = fullfile(folder_path, directory_entry) ;
        if is_this_directory_entry_a_folder ,
            % if a folder, recurse
            job_ids = ...
                find_and_batch_helper(base_folder_path, ...
                                      directory_entry_path, ...
                                      file_name_regexp, ...
                                      batch_function, ...
                                      do_submit, ...
                                      job_ids, ...
                                      varargin{:}) ;
        else
            if does_match_regexp(directory_entry, file_name_regexp) ,
                job_id = ...
                    bsub(do_submit, ...
                         '-n1 -P mouselight -W 59 -J overwrite-raw-tile-with-line-fixed', ...
                         batch_function, ...
                         directory_entry_path, ...
                         base_folder_path, ...
                         varargin{:}) ;
                job_ids = horzcat(job_ids, job_id) ; %#ok<AGROW>
            end
        end
    end    
end
