function is_all_well = find_and_verify(root_folder_path, file_name_predicate, verify_function, varargin)
    tic_id = tic() ;
    verified_ok_count = 0 ;
    problem_paths = cell(1,0) ;
    [verified_ok_count, problem_paths] = ...
        find_and_verify_helper(root_folder_path, ...
                               file_name_predicate, ...
                               verify_function, ...                               
                               verified_ok_count, ...
                               problem_paths, ...
                               varargin{:}) ;
    if isempty(problem_paths) ,
        fprintf(['All files with names matching the predicate function %s() in folder \n' ...
                 '    %s\n' ...
                 '    were successfully verified with function %s().\n'], ...
                func2str(file_name_predicate), ...
                root_folder_path, ...
                func2str(verify_function)) ;
        fprintf('Hooray!\n') ;
        fprintf('%d files checked\n', verified_ok_count) ;
        is_all_well = true ;
    else        
        for i = 1 : length(problem_paths) ,
            fprintf('File %s failed verification with function %s()\n', problem_paths{i}, func2str(verify_function)) ;
        end
        fprintf('Boo!\n') ;
        is_all_well = false ;
    end    
    elapsed_time = toc(tic_id) ;
    fprintf('Elapsed time for verifcation was %g seconds.\n', elapsed_time) ;
end



function [verified_ok_count, problem_paths] = ...
        find_and_verify_helper(current_folder_path, ...
                               file_name_predicate, ...
                               verify_function, ...
                               verified_ok_count, ...
                               problem_paths, ...
                               varargin)
                                                 
    [file_names, is_file_a_folder] = simple_dir(current_folder_path) ;
    raw_tiles_input_entity_count = length(file_names) ;
    for i = 1 : raw_tiles_input_entity_count ,
        file_name = file_names{i} ;        
        is_this_file_a_folder = is_file_a_folder(i) ;
        file_path = fullfile(current_folder_path, file_name) ;
        if is_this_file_a_folder ,
            % if a folder, recurse
            [verified_ok_count, problem_paths] = ...
                find_and_verify_helper(file_path, ...
                                       file_name_predicate, ...
                                       verify_function, ...
                                       verified_ok_count, ...
                                       problem_paths, ...
                                       varargin{:}) ;
        else
            %tif_input_entity_path = fullfile(tif_input_folder_name, tif_input_entity_name) ;    
            %[~,~,ext] = fileparts(raw_tiles_input_entity_name) ;
            if feval(file_name_predicate, file_name)  ,
                % If source is a tif with the right kind of name, check for the corresponding checkpoint files                
                is_verified = feval(verify_function, file_path, varargin{:}) ;
                if is_verified ,
                    verified_ok_count = verified_ok_count + 1 ;
                else
                    problem_paths = horzcat(problem_paths, {file_path}) ;  %#ok<AGROW>
                end
            end
        end
    end    
end
