function generate_fragments_from_named_tree(fragment_output_folder_path, ...
                                            named_tree, ...
                                            file_format, ...
                                            minimum_centerpoint_count_per_fragment, ...
                                            bounding_box_low_corner_xyz, ...
                                            bounding_box_high_corner_xyz)

    if isequal(file_format, 'swc') ,
        % Save as lots of .swc files
        generate_fragments_as_swcs_from_named_tree(fragment_output_folder_path, ...
                                                   named_tree, ...
                                                   minimum_centerpoint_count_per_fragment, ...
                                                   bounding_box_low_corner_xyz, ...
                                                   bounding_box_high_corner_xyz)
    elseif isequal(file_format, 'mat') ,
        % Save as a single .mat file
        write_fragments_as_single_mat_given_named_tree(fragment_output_folder_path, ...
                                                       named_tree, ...
                                                       minimum_centerpoint_count_per_fragment, ...
                                                       bounding_box_low_corner_xyz, ...
                                                       bounding_box_high_corner_xyz) ;
    else
        error('Don''t recognize format "%s"', file_format) ;        
    end
end
