% Set up the par pool
use_this_fraction_of_cores(1) ;

% Build the tile index for the subset
tile_index = compute_or_read_from_memo(subset_memo_folder_path, ...
                                       'subsset-raw-tile-index', ...
                                       @()(build_raw_tile_index_for_neighborhood(raw_tile_root_folder_path, ...
                                                                                 center_tile_relative_path, ...
                                                                                 sample_memo_folder_path)), ...
                                       do_force_computation) ;
