function result = named_tree_struct(m, n) 
    empty = cell(m,n) ;
    result = struct('name', empty, ...
                    'xyz', empty, ...
                    'r', empty, ...
                    'parent', empty, ...
                    'tag_code', empty) ;
end
