function save_swc_arrays(output_folder_path, ...                         
                         forest_as_swc_arrays)
    
    % Generate colormap
    tree_count = length(forest_as_swc_arrays) ;
    raw_color_from_tree_id = jet(tree_count);
    color_from_tree_id = raw_color_from_tree_id(randperm(tree_count),:) ;

    % Create the folder if it doesn't exist
    if tree_count>0 && ~exist(output_folder_path, 'file') ,
        mkdir(output_folder_path) ;
    end    
    
    % Write each fragment to disk as a .swc file
    for tree_index = 1:tree_count ,
        % .swc file name
        swc_base_name = sprintf('tree-%d', tree_index) ;
        swc_file_name = horzcat(swc_base_name, '.swc') ;
        swc_file_path = fullfile(output_folder_path, swc_file_name);

        % If the output file already exists, skip it
        if exist(swc_file_path, 'file') ,
            continue ;
        end
        
        % Get the centerpoints for this neuron
        tree_as_swc_array = forest_as_swc_arrays{tree_index} ;
        tree_xyzs = tree_as_swc_array(:,3:5) ;

        % Center centerpoint coordinates on the center of mass
        tree_centroid_xyz = mean(tree_xyzs, 1) ;        
        tree_xyzs_centered = tree_xyzs - tree_centroid_xyz ;
        
        % Create .swc data matrix
        centered_tree_as_swc_array = tree_as_swc_array ;
        centered_tree_as_swc_array(:,3:5) = tree_xyzs_centered ;
        
        % Write swc
        fid = fopen(swc_file_path,'w') ;
        mytxt = sprintf('# Generated by save_swc_arrays()\n');
        fprintf(fid,'%s',mytxt);
        mytxt = sprintf('# OFFSET %.6f %.6f %.6f\n',tree_centroid_xyz);
        fprintf(fid,'%s',mytxt);
        mytxt = sprintf('# COLOR %f,%f,%f\n', ...
                        color_from_tree_id(tree_index,1), ...
                        color_from_tree_id(tree_index,2), ...
                        color_from_tree_id(tree_index,3)) ;
        fprintf(fid,'%s',mytxt);
        mytxt = sprintf('# NAME %s\n',swc_base_name);
        fprintf(fid,'%s',mytxt);
        fprintf(fid,'%d %d %f %f %f %d %d\n',centered_tree_as_swc_array');
        fclose(fid);
    end
end
