function write_fragments_as_single_mat_given_named_tree(fragment_output_folder_path, ...
                                                        named_tree, ...
                                                        minimum_centerpoint_count_per_fragment, ...
                                                        bounding_box_low_corner_xyz, ...
                                                        bounding_box_high_corner_xyz)

    % Generate the file name for this file
    fragments_mat_file_name = sprintf('%s-fragments.mat', named_tree.name) ;
    fragments_mat_file_path = fullfile(fragment_output_folder_path, fragments_mat_file_name);
    
    % If the output file already exists, skip it
    if exist(fragments_mat_file_path, 'file') ,
        return
    end
    
    % Break the tree into fragments, in main memory
    fragments_as_named_trees = ...
        named_forest_of_fragments_from_named_tree(named_tree, ...
                                                  minimum_centerpoint_count_per_fragment, ...
                                                  bounding_box_low_corner_xyz, ...
                                                  bounding_box_high_corner_xyz) ;
 
    % Save these fragments to a file
    save(fragments_mat_file_path, '-v7.3', 'fragments_as_named_trees') ;                                                       
end
