% Specify the input/output folders
sample_tag = '2021-09-16'  %#ok<NOPTS>
analysis_tag = 'p-map-render' 
this_folder_path = fileparts(mfilename('fullpath')) ;
%tile_folder_path = '/groups/mousebrainmicro/mousebrainmicro/data/2021-09-16/Tiling'
tile_folder_path = '/nrs/mouselight/pipeline_output/2021-09-16/stage_2_classifier_output'  % this will get the p-map tiles
pipeline_output_folder = '/nrs/mouselight/pipeline_output/2021-09-16'
sample_memo_folder_path = fullfile('/groups/mousebrainmicro/mousebrainmicro/cluster/Reconstructions', sample_tag) ;
analysis_memo_folder_path = fullfile(sample_memo_folder_path, analysis_tag) ;
stitching_output_folder_path = fullfile(analysis_memo_folder_path, 'stitching-output') ;
vecfield3D_file_path = ...
    strcat('/groups/mousebrainmicro/mousebrainmicro/cluster/Reconstructions/2021-09-16/', ...
           'production-classifier-z-match-count-threshold-50/stitching-output/vecfield3D.mat') ;
notifications_email_address = 'taylora@hhmi.org' ;
is_p_map = true ;

% Call the function that does the real work
render(sample_tag, ...
       analysis_tag, ...
       tile_folder_path, ...
       vecfield3D_file_path, ...
       analysis_memo_folder_path, ...
       notifications_email_address, ...
       is_p_map) ;
