function run_pointmatch_on_single_pair(raw_tiles_path, ...
                                       descriptors_path, ...
                                       z_point_match_path, ...
                                       central_tile_relative_path, ...
                                       central_tile_ijk1, ...
                                       other_tile_relative_path, ...
                                       sample_metadata, ...
                                       do_run_in_debug_mode)

    % Set paths to inputs, outputs
    central_tile_landmark_folder_path = fullfile(descriptors_path, central_tile_relative_path) ;
    other_tile_landmark_folder_path = fullfile(descriptors_path, other_tile_relative_path) ;
    central_tile_raw_folder_path = fullfile(raw_tiles_path, central_tile_relative_path) ;
    other_tile_raw_folder_path = fullfile(raw_tiles_path, other_tile_relative_path) ;
    output_folder_path = fullfile(z_point_match_path, central_tile_relative_path) ;
    
    % Run the code under test
    manual_nominal_other_tile_ijk_offset = [] ;
    maximum_landmark_count = 10000 ;
    pointmatch(central_tile_landmark_folder_path, ...
               other_tile_landmark_folder_path, ...
               central_tile_raw_folder_path, ...
               other_tile_raw_folder_path, ...
               output_folder_path, ...
               sample_metadata, ...
               manual_nominal_other_tile_ijk_offset, ...
               central_tile_ijk1, ...
               maximum_landmark_count, ...
               do_run_in_debug_mode) ;
end
