function result = corrected_targets_for_single_cpg_k_plane(k0, ...
                                                           field_corrected_cpg_ij0s, ...
                                                           affine_transform, ...
                                                           Fx, ...
                                                           Fy, ...
                                                           Fz, ...
                                                           do_correct_targets)
    % Use the interpolators Fx, Fy, Fz to generate corrected rendered-space
    % targets for a single z plane of the CPG grid for the tile.
    cpg_ij_count = size(field_corrected_cpg_ij0s, 1) ;
    field_corrected_cpg_ijk0s = [ field_corrected_cpg_ij0s repmat(k0, [cpg_ij_count 1]) ] ;
    baseline_targets = add_ones_column(field_corrected_cpg_ijk0s) * affine_transform' ;
    if do_correct_targets , 
        target_shift = ...
            [Fx(baseline_targets) Fy(baseline_targets) Fz(baseline_targets)] ;
        result = baseline_targets + target_shift ;
    else
        result = baseline_targets ;
    end
end
