function run_ilastik_on_stack(output_file_path, input_file_name, ilastik_project_file_name)
    % Get path to this script's folder, b/c Ilastik .ilp files are in the same
    % folder
    script_folder_path = fileparts(mfilename('fullpath')) ;
    
    production_classifier_ilastik_project_file_name = 'axon_uint16.ilp' ;
    if ~exist('ilastik_project_file_name', 'var') || isempty(ilastik_project_file_name) || ...
            strcmp(ilastik_project_file_name, production_classifier_ilastik_project_file_name) ,
        % Use the production classifier    
        ilastik_project_path = ...
            fullfile(script_folder_path, production_classifier_ilastik_project_file_name) ;
        ilastik_root_path = '/groups/mousebrainmicro/mousebrainmicro/pipeline-systems/tools/ilastik-1.1.9-Linux' ;
        % The production classifier is designed to be used with Ilastik 1.1.9,
        % which seems to compress HDF5 output files by default.
        % In all cases, we want the output files to be compressed HDF5.
        output_format = 'hdf5' ;
    else
        ilastik_project_path = ...
            fullfile(script_folder_path, ilastik_project_file_name) ;
        % Use newer Ilastik if user has specified a non-production classifier
        ilastik_root_path = ...
            '/groups/mousebrainmicro/mousebrainmicro/pipeline-systems/tools/ilastik-1.3.3-Linux' ;       
        % The production classifier is designed to be used with Ilastik 1.1.9,
        % which seems to compress HDF5 output files by default.
        % In all cases, we want the output files to be compressed HDF5.
        output_format = 'compressed hdf5' ;
    end
    
    %'multipage tiff', 'multipage tiff sequence', 'hdf5'
    python_path = fullfile(ilastik_root_path, 'bin/python') ;
    ilastik_dot_py_path = fullfile(ilastik_root_path, 'ilastik-meta/ilastik/ilastik.py') ;
    command_line = sprintf(['export LAZYFLOW_THREADS=4 ; ' ...
                            'export LAZYFLOW_TOTAL_RAM_MB=60000 ; ' ...
                            '"%s" ' ...
                            '"%s" ' ...
                            '--headless ' ...
                            '--readonly 1 ' ...
                            '--cutout_subregion="[(None,None,None,0),(None,None,None,1)]" ' ...
                            '--project="%s" ' ...
                            '--output_filename_format="%s" ' ...
                            '--output_format="%s" ' ...
                            '"%s"'] , ...
                           python_path, ...
                           ilastik_dot_py_path, ...
                           ilastik_project_path, ...
                           output_file_path, ...
                           output_format, ...
                           input_file_name) ;                           
    fprintf('Ilastik command line: %s\n', command_line) ;                   
    system_with_error_handling(command_line) ;   
end
