function batch_convert_all_mj2_files_to_tif(output_folder_name, ...
                                            input_folder_name, ...
                                            do_submit, ...
                                            do_try, ...
                                            maximum_running_slot_count, ...
                                            submit_host_name)
    % Find all .mj2 files in folders with no subfolders, convert them to .tif
    
    slots_per_job = 1 ;
    bsub_options = '-P mouselight -W 59 -J thaw' ;
    find_and_batch(input_folder_name, ...
                   @is_a_mj2_and_target_missing, ...
                   @tif_from_mj2_single_for_find_and_batch, ...
                   'do_submit', do_submit, ...
                   'do_try', do_try, ...
                   'submit_host_name', submit_host_name, ...
                   'maximum_running_slot_count', maximum_running_slot_count, ...
                   'slots_per_job', slots_per_job, ...
                   'bsub_options', bsub_options, ...
                   'predicate_extra_args', {input_folder_name, output_folder_name}, ...
                   'batch_function_extra_args', {input_folder_name, output_folder_name}) ;
end
