sample_date = '2023-02-23' ;
mj2_output_folder_path = sprintf('/nrs/mouselight/SAMPLES/2023-02-23/%s', sample_date) ;
tif_input_folder_path = sprintf('/nrs/mouselight/SAMPLES/TO_NEARLINE/%s', sample_date) ;
compression_ratio = 10 ;
do_run_on_cluster = true ;
do_try = true ;  % not used
maximum_running_slot_count = 500 ;
submit_host_name = if_not_a_submit_host('login2.int.janelia.org') ;

freeze_mouselight_folder(mj2_output_folder_path, ...
              tif_input_folder_path, ...
              compression_ratio, ...
              do_run_on_cluster, ...
              do_try, ...
              maximum_running_slot_count, ...
              submit_host_name) ;

