function rebuild_tif_octree_from_leaves(root_folder_path)
    path_from_leaf_stack_index = ...
        find_and_list(root_folder_path, ...
                      @is_a_tif_in_a_folder_with_no_subfolders) ;
end
