do_verify = false ;
do_on_cluster = true ;

tif_from_mj2('/groups/mousebrainmicro/mousebrainmicro/data/2017-12-19-thawed', ...
             '/groups/mousebrainmicro/mousebrainmicro/data/2017-12-19', ...
             do_verify, ...
             do_on_cluster) ;
